version: '3.1'
services:
  stats-server:
    build: ./ewm-stat-service/stat_service
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"

    depends_on:
      - stats-db
    environment:
      - STATS_CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6062:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ./ewm-main-service
    image:
      ewm-service:latest
    container_name: ewm-service
    ports:
      - "8080:8080"

    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-service

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
