CREATE TABLE IF NOT EXISTS categories (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name varchar(120) NOT NULL CHECK (name <> ''),
                                          CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
                                     id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar,
                                     email varchar,
                                     CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      initiator_id int8 REFERENCES users (id),
                                      annotation varchar(2000) NOT NULL,
                                      category_id int8 REFERENCES categories (id),
                                      description varchar(7000),
                                      event_date timestamp NOT NULL,
                                      created_on timestamp NOT NULL,
                                      published_on timestamp,
                                      lat float NOT NULL,
                                      lon float NOT NULL,
                                      paid boolean,
                                      participant_limit int4,
                                      request_moderation boolean,
                                      title varchar(120) NOT NULL,
                                      state varchar(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        event_id int8 REFERENCES events (id),
                                        requester_id int8 REFERENCES users (id),
                                        status varchar NOT NULL,
                                        created_on timestamp NOT NULL,
                                        CONSTRAINT user_event_pk UNIQUE (requester_id, event_id)
);

CREATE TABLE IF NOT EXISTS compilations (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            pinned boolean NOT NULL,
                                            title varchar(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_event (
                                                 compilation_id BIGINT REFERENCES compilations (id),
                                                 event_id BIGINT REFERENCES events (id),
                                                 CONSTRAINT comp_event_pk primary key (compilation_id, event_id)
);
